apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: route-finale
type: Opaque
stringData:
  mysql-root-password: "root123"
  mysql-database: "wpdb"
  mysql-user: "wpuser"
  mysql-password: "wp12345"
