apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - mysql/secret.yaml
  - mysql/pvc.yaml
  - mysql/service.yaml
  - mysql/deployment.yaml
  - wordpress/configmap.yaml
  - wordpress/service.yaml
  - wordpress/deployment.yaml
  - ingress.yaml
