---
- name: Ensure build directories exist
  file:
    path: "/tmp/builds/{{ item }}"
    state: directory
    mode: '0755'
  loop:
    - wordpress
    - temp

- name: Copy build scripts
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: '0755'
  loop:
    - { src: "../../../scripts/deploy.sh", dest: "/tmp/builds/deploy.sh" }
    - { src: "../../../scripts/test.sh", dest: "/tmp/builds/test.sh" }